CREATE TABLE Users (
    Email VARCHAR(100) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Surname VARCHAR(100),
    Password VARCHAR(80) NOT NULL,
    Photo TEXT,
    Logo TEXT
);

CREATE TABLE Client (
    ID SERIAL NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Profession VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    Gender CHAR(1) NOT NULL,
    BirthDate DATE NOT NULL,
    Address VARCHAR(200),
    AddressNumber VARCHAR(10),
    AddressComplement VARCHAR(50),
    MaritalStatus VARCHAR(20) NOT NULL,
    PartnerName VARCHAR(100),
    PartnerEmail VARCHAR(100),
    PartnerPhoneNumber VARCHAR(15),
    PartnerGender CHAR(1),
    PartnerProfession VARCHAR(100),
    UserEmail VARCHAR(100) NOT NULL
);

CREATE TABLE Dependent (
    ID SERIAL NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Gender CHAR(1) NOT NULL,
    BirthDate DATE NOT NULL,
    PhoneNumber VARCHAR(15),
    Type VARCHAR(50) NOT NULL,
    ClientID INT NOT NULL
);

CREATE TABLE UserReport (
    ID SERIAL NOT NULL,
    Title VARCHAR(100),
    Content TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserEmail VARCHAR(100) NOT NULL
);

CREATE TABLE ClientReport (
    ID SERIAL NOT NULL,
    Title VARCHAR(100),
    Content TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ClientID INT NOT NULL
);

ALTER TABLE Users
    ADD CONSTRAINT PK_Users PRIMARY KEY (Email);

ALTER TABLE Client
    ADD CONSTRAINT PK_Client PRIMARY KEY (ID),
    ADD CONSTRAINT FK_Client_Users FOREIGN KEY (UserEmail) REFERENCES Users(Email) ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT UQ_Client_Email UNIQUE (Email);

ALTER TABLE Dependent
    ADD CONSTRAINT PK_Dependent PRIMARY KEY (ID),
    ADD CONSTRAINT FK_Dependent_Client FOREIGN KEY (ClientID) REFERENCES Client(ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE UserReport
    ADD CONSTRAINT PK_UserReport PRIMARY KEY (ID),
    ADD CONSTRAINT FK_UserReport_Users FOREIGN KEY (UserEmail) REFERENCES Users(Email) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ClientReport
    ADD CONSTRAINT PK_ClientReport PRIMARY KEY (ID),
    ADD CONSTRAINT FK_ClientReport_Client FOREIGN KEY (ClientID) REFERENCES Client(ID) ON DELETE CASCADE ON UPDATE CASCADE;